config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
dotfiles:
  f_dms_default:
    src: config/DarkMaterialShell/settings.json
    dst: ~/.config/DarkMaterialShell/settings.json
  f_dms_defiant:
    src: config/DarkMaterialShell/settings_defiant.json
    dst: ~/.config/DarkMaterialShell/settings.json
  f_dms_dauntless:
    src: config/DarkMaterialShell/settings_dauntless.json
    dst: ~/.config/DarkMaterialShell/settings.json
  f_hyprland_default:
    src: config/hypr/hyprland.conf
    dst: ~/.config/hypr/hyprland.conf
  f_hyprland_default_monitors:
    src: config/hypr/default_monitors.conf
    dst: ~/.config/hypr/monitors.conf
  f_hyprland_defiant_monitors:
    src: config/hypr/defiant_monitors.conf
    dst: ~/.config/hypr/monitors.conf
  f_hyprland_dauntless_monitors:
    src: config/hypr/dauntless_monitors.conf
    dst: ~/.config/hypr/monitors.conf
  f_btop:
    src: config/btop/btop.conf
    dst: ~/.config/btop/btop.conf
  f_fastfetch:
    src: config/fastfetch/confg.jsonc
    dst: ~/.config/fastfetch/config.jsonc
  f_ghostty:
    src: config/ghostty/config
    dst: ~/.config/ghostty/config
  f_udiskie:
    src: config/udiskie/config.yml
    dst: ~/.config/udiskie/config.yml
  f_nano:
    src: config/.nanorc
    dst: ~/.config/.nanorc
profiles:
  default:
    dotfiles:
    - f_dms_default
    - f_hyprland_default
    - f_hyprland_default_monitors
    - f_btop
    - f_fastfetch
    - f_ghostty
    - f_udiskie
    - f_nano
  defiant:
    dotfiles:
    - f_dms_default
    - f_hyprland_default
    - f_hyprland_defiant_monitors
    - f_btop
    - f_fastfetch
    - f_ghostty
    - f_udiskie
    - f_nano
  dauntless:
    dotfiles:
    - f_dms_default
    - f_hyprland_default
    - f_hyprland_dauntless_monitors
    - f_btop
    - f_fastfetch
    - f_ghostty
    - f_udiskie
    - f_nano
  titan:
    dotfiles:
    - f_dms_default
    - f_hyprland_default
    - f_hyprland_titan_monitors
    - f_btop
    - f_fastfetch
    - f_ghostty
    - f_udiskie
    - f_nano