config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
dotfiles:
  f_dms_default:
    src: config/DankMaterialShell/settings.json
    dst: ~/.config/DankMaterialShell/settings.json
  f_dms_defiant:
    src: config/DankMaterialShell/defiant.json
    dst: ~/.config/DankMaterialShell/settings.json
  f_dms_dauntless:
    src: config/DankMaterialShell/dauntless.json
    dst: ~/.config/DankMaterialShell/settings.json
  f_dms_intrepid:
    src: config/DankMaterialShell/intrepid.json
    dst: ~/.config/DankMaterialShell/settings.json
  f_hyprland_default:
    src: config/hypr/hyprland.conf
    dst: ~/.config/hypr/hyprland.conf
  f_hyprland_defiant:
    src: config/hypr/defiant.conf
    dst: ~/.config/hypr/hyprland.conf
  f_hyprland_dauntless:
    src: config/hypr/dauntless.conf
    dst: ~/.config/hypr/hyprland.conf
  f_hyprland_intrepid:
    src: config/hypr/intrepid.conf
    dst: ~/.config/hypr/hyprland.conf
profiles:
  default:
    dotfiles:
    - f_dms_default
    - f_hyprland_default
  defiant:
    dotfiles:
    - f_dms_defiant
    - f_hyprland_defiant
  dauntless:
    dotfiles:
    - f_dms_dauntless
    - f_hyprland_dauntless
  intrepid:
    dotfiles:
    - f_dms_intrepid
    - f_hyprland_intrepid