config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
dotfiles:
  f_dms_default:
    src: config/DankMaterialShell/settings.json
    dst: ~/.config/DankMaterialShell/settings.json
  f_hyprland_nsweeting:
    src: config/hypr/hyprland.conf
    dst: ~/.config/hypr/hyprland.conf
profiles:
  default:
    dotfiles:
    - f_dms_default
    - f_hyprland_nsweeting